apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  default.conf: |-
    upstream gateway-k8s {
          server gateway-service;
    }
    server {
            listen  80;
            server_name  localhost;

            root    /web/dist;
            index   index.html index.htm;

            location / {
    	       try_files $uri $uri/ /index.html;
    	    }


            location /backEnd1 {
                proxy_pass http://gateway-k8s;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;

                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $host;
                proxy_set_header   X-Real-IP         $remote_addr;
            }

            location ^~ /backEnd2 {
                proxy_pass http://gateway-k8s;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_redirect     off;

                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $host;
                proxy_set_header   X-Real-IP         $remote_addr;
             }

            location /date {
                add_header Access-Control-Expose-Headers "Date";
                add_header Access-Control-Allow-Headers 'content-type,Cache-Control,Pragma,Date';
                empty_gif;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }
    }